export const AksaTeam = [
  {
    name: 'Zvjezdan Turkić',
    img: {
      src: '/slike/tim/member-1.jpg',
      alt: 'Zvjezdan Turkić',
      width: 290,
      height: 290,
    },
    title: '',
    titleEn: '',
    position: 'Vlasnik i osnivač',
    positionEn: 'Owner and Founder',
  },
  {
    img: {
      src: '/slike/tim/member-2.jpg',
      alt: 'Senaida Turkić',
      width: 473,
      height: 824,
    },
    name: 'Senaida Turkić',
    title: '',
    titleEn: '',
    position: 'Generalni direktor',
    positionEn: 'CEO',
  },
  {
    img: {
      src: '/slike/tim/member-4.jpg',
      alt: 'Jagoda Softić',
      width: 473,
      height: 824,
    },
    name: 'Jagoda Softić',
    title: '',
    titleEn: '',
    position: 'Finansijski direktor',
    positionEn: 'Chief Financial Officer',
  },
  {
    img: {
      src: '/slike/tim/member-3.jpg',
      alt: 'Haris Turkić',
      width: 290,
      height: 290,
    },
    name: 'Haris Turkić',
    title: '',
    titleEn: '',
    position: 'Tehnički direktor',
    positionEn: 'Head of Engineering',
  },
  {
    img: {
      src: '/slike/tim/sanda.jpg',
      alt: 'Sanda Osvald',
      width: 473,
      height: 824,
    },
    name: 'Sanda Osvald',
    title: '',
    titleEn: '',
    position: 'Rukovodilac odjela za arhitektonsko projektovanja ',
    positionEn: 'Head of Department of Architectural Design',
  },
  {
    img: {
      src: '/slike/tim/member-13.jpg',
      alt: 'Ajla Turkić',
      width: 473,
      height: 824,
    },
    name: 'Ajla Turkić',
    title: '',
    titleEn: '',
    position: 'Rukovodilac odjela za fasadni inženjering',
    positionEn: 'Head of Department of Facade Engineering',
  },
  {
    img: {
      src: '/slike/tim/member-5.jpg',
      alt: 'Nejla Borić',
      width: 473,
      height: 824,
    },
    name: 'Nejla Borić',
    title: '',
    titleEn: '',
    position: 'Glavni inženjer za projektovanje',
    positionEn: 'Senior Architect',
  },
  {
    img: {
      src: '/slike/tim/marin.jpg',
      alt: 'Marin Šimić',
      width: 290,
      height: 290,
    },
    name: 'Marin Šimić',
    title: '',
    titleEn: '',
    position: 'Glavni inženjer za projektovanje',
    positionEn: 'Senior Architect',
  },
  {
    img: {
      src: '/slike/tim/member-6.jpg',
      alt: 'Lamija Mešeljević',
      width: 473,
      height: 824,
    },
    name: 'Lamija Mešeljević',
    title: '',
    titleEn: '',
    position: 'Glavni inženjer',
    positionEn: 'Senior Engineer',
  },
  {
    img: {
      src: '/slike/tim/member-8.jpg',
      alt: 'Andrea Meh. Grgić',
      width: 473,
      height: 824,
    },
    name: 'Andrea Meh. Grgić',
    title: '',
    titleEn: '',
    position: 'Saradnik inženjer za projektovanje',
    positionEn: 'Structural Engineer',
  },
  {
    img: {
      src: '/slike/tim/dzenana.jpg',
      alt: 'Dženana Huseinbašić',
      width: 473,
      height: 824,
    },
    name: 'Dženana Huseinbašić',
    title: '',
    titleEn: '',
    position: 'Saradnik inženjer za projektovanje',
    positionEn: 'Structural Engineer',
  },
  {
    img: {
      src: '/slike/tim/member-9.jpg',
      alt: 'Safeta Zimeri',
      width: 473,
      height: 824,
    },
    name: 'Safeta Zimeri',
    title: '',
    titleEn: '',
    position: 'Odgovormi inženjer',
    positionEn: 'Engineer',
  },
  {
    img: {
      src: '/slike/tim/member-10.jpg',
      alt: 'Ilhan Šarić',
      width: 290,
      height: 290,
    },
    name: 'Ilhan Šarić',
    title: '',
    titleEn: '',
    position: 'Odgovorni inženjer',
    positionEn: 'Engineer',
  },
  {
    img: {
      src: '/slike/tim/adna-puljic.jpg',
      alt: 'Adna Puljić-Zukić',
      width: 290,
      height: 290,
    },
    name: 'Adna Puljić-Zukić',
    title: '',
    titleEn: '',
    position: 'Inženjer',
    positionEn: 'Junior Engineer',
  },
  {
    img: {
      src: '/slike/tim/member-11.jpg',
      alt: 'Haris Bjelošević',
      width: 290,
      height: 290,
    },
    name: 'Haris Bjelošević',
    title: '',
    titleEn: '',
    position: 'Viši tehnički crtač za konstrukciju',
    positionEn: 'Senior Structural Drafter',
  },
  {
    img: {
      src: '/slike/tim/kenan.jpg',
      alt: 'Kenan Mešeljević',
      width: 290,
      height: 290,
    },
    name: 'Kenan Mešeljević',
    title: '',
    titleEn: '',
    position: 'Tehnički crtač',
    positionEn: 'Technical Drafter',
  },
  {
    img: {
      src: '/slike/tim/member-12.jpg',
      alt: 'Željka Bektaš',
      width: 473,
      height: 824,
    },
    name: 'Željka Bektaš',
    title: '',
    titleEn: '',
    position: 'Sekretar',
    positionEn: 'Secretary',
  },
  {
    name: 'Zvjezdan Turkić',
    img: {
      src: '/slike/tim/member-15.jpg',
      alt: 'Zvjezdan Turkić',
      width: 290,
      height: 290,
    },
    title: '',
    titleEn: '',
    position: 'Vlasnik i osnivač i vlasnik',
    positionEn: 'Owner and Founder and Owner',
  },
];
